sudo: required

language: go

services:
  - docker

before_install:
  - docker-compose build
  - docker-compose pull
  - docker login -u _ --password $HEROKU_TOKEN registry.heroku.com

script:
  - exit 0

deploy:
  provider: script
  script: docker tag web registry.heroku.com/patecho-ci/web && docker push registry.heroku.com/patecho-ci/web
  on:
    branch: master
  provider: script
  script: docker tag sonarqube registry.heroku.com/patecho-ci/sonarqube && docker push registry.heroku.com/patecho-ci/sonarqube
  on:
    branch: master
