sudo: required

services:
  - docker

stages:
  - build
  - pull
  - heroku-docker-login
  - tag
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: build
      script: docker-compose build
    - stage: pull
      script: docker-compose pull
    - stage: heroku-docker-login
      script: docker login -u _ --password $HEROKU_TOKEN registry.heroku.com

    - stage: tag
      script: docker tag web registry.heroku.com/patecho-ci/web
    - script: docker tag sonarqube registry.heroku.com/patecho-ci/sonarqube

    - stage: deploy
      script: docker push registry.heroku.com/patecho-ci/web
    - script: docker push registry.heroku.com/patecho-ci/sonarqube
