sudo: required

services:
  - docker

cache:
  bundler: true
  directories:
    - $HOME/docker

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

stages:
  - build and pull
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: build and pull
      script: docker-compose build && docker-compose pull

    - stage: deploy
      script:
        - >
          docker login -u _ --password $HEROKU_TOKEN registry.heroku.com &&
          docker tag githubsevedosye_web registry.heroku.com/patecho-ci/web
          docker push registry.heroku.com/patecho-ci/web

    - script:
        - >
          docker login -u _ --password $HEROKU_TOKEN registry.heroku.com &&
          docker tag sonarqube registry.heroku.com/patecho-ci/sonarqube &&
          docker push registry.heroku.com/patecho-ci/sonarqube
